### ISSUE TITLE
mos build error: "error: implicit declaration of function 'mgos_invoke_cb'"

### ISSUE THREAD

**Issue by jknutson** [mongoose-os-libs/dns-sd#4]
I just started seeing this error when trying to run `mos build` for an app where this library was included.

```
/data/fwbuild-volumes/latest/apps/esp32-temp-js/esp32/build_contexts/build_ctx_772198382/deps/dns-sd/src/mongoose/mgos_dns_sd.c: In function 'mgos_dns_sd_advertise':
/data/fwbuild-volumes/latest/apps/esp32-temp-js/esp32/build_contexts/build_ctx_772198382/deps/dns-sd/src/mongoose/mgos_dns_sd.c:400:3: error: implicit declaration of function 'mgos_invoke_cb' [-Werror=implicit-function-declaration]
   mgos_invoke_cb(mgos_dns_sd_advertise2, (void *) 0, false /* from_isr */);
   ^
```

I think this is related to [this commit](https://github.com/mongoose-os-libs/dns-sd/commit/369fd40a38e93c1465669a3ddc237faba1ee63b7#diff-dc5eed80242ef75c6338b2c6eeb0f273383d8958b30d1bd55628db92268ba995R400)

If my C skills were a little better, I'd try to PR/fix it myself!

**Comment by rojer** [comment]
indeed, you are right. sorry about that, fixed now!
