### ISSUE TITLE
Multiple interface support

### ISSUE THREAD

**Issue by kzyapkov** [mongoose-os-libs/dns-sd#6]
Currently, at least on esp32, DNS-SD refuses to work if both `sta` and `ap` WiFi modes are enabled.

However, it has no issues with the STA fallbacks, `sta1`, `sta2`, and with `ethernet`. Depending on the circumstances, mDNS advertisements over these interfaces either lack the A records or advertise the wrong IP address. For example, if both STA and Ethernet are up, one gets the STA IP over Ethernet.

Please implement support for multiple interfaces.

**Comment by rojer** [comment]
fixed by https://github.com/mongoose-os-libs/dns-sd/commit/ac231e312f12f0ce139d71b117402b5f2f9f2449
