### ISSUE TITLE
Add delayed initialization, or functions to init and deinit DNS-SD

### ISSUE THREAD

**Issue by tripflex** [mongoose-os-libs/dns-sd#6]
I'm having an issue when my device boots up of being flooded with MDNS packets from Chromecast and other devices, causing a fault due to memory issues.  This isn't a problem normally once the device fully boots but randomly during the boot process due to limited memory it causes heap errors.

Would be nice to have the ability to delay initialization of DNS-SD with a timer value, as well as some exposed functions we could use to both initialize and de-initialize DNS-SD.  

Having the available functions to init/de-init DNS-SD would allow me to manually init and deinit it as needed (without need for delayed init)

**Comment by rojer** [comment]
makes sense, i think option 3 would be the easiest to implement and would solve your problem.

**Comment by tripflex** [comment]
@rojer what about instead, just adding the config setting like `dns_sd.adv_only` to only advertise and not subscribe to multicast group?  I was able to resolve my issues by just commenting out the code that joins the multicast group (15+ chromecast devices on network caused ~64904 memory usage randomly when it seems they all send at the same time).

Reason I say this is because `advertise_type()` appears to add all the records and advertise with anyways, so at least in my situation -- there's no need to **also** respond to DNS queries as a flood of them on the network can bring the device down (or at least throw heap errors)

**Comment by rojer** [comment]
makes sense, go ahead.
