### ISSUE TITLE
mgos_dns_sd.h content unavailable to compiler somehow

### ISSUE THREAD

**Issue by d4rkmen** [mongoose-os-libs/dns-sd#7]
Included the library inside my custom library with "libs:  - origin" include file founds ok but cant see any declarations (#include "mgos_dns_sd.h")
"#pragma once" - seems to work incorrect
replaced with
#ifndef CS_MOS_LIBS_DNS_SD_INCLUDE_MGOS_DNS_SD_H_
#define CS_MOS_LIBS_DNS_SD_INCLUDE_MGOS_DNS_SD_H_
and all ok

Thanks for a great usefull lib

**Comment by rojer** [comment]
ok, we'll need to dig into it.
i'll need an example where it fails

**Comment by d4rkmen** [comment]
**libs:**
  - origin: https://github.com/mongoose-os-libs/dns-sd

**main.c**

#include "mgos_homekit.h"
#include "mgos_dns_sd.h"
...
struct mgos_dns_sd_txt_entry hap_service_txt[] = {
    {.key = "c#", .value = "1"},
..
/data/fwbuild-volumes/2.16.0/apps/app1/esp8266/build_contexts/build_ctx_496914074/src/main.c: In function 'mgos_app_init':
/data/fwbuild-volumes/2.16.0/apps/app1/esp8266/build_contexts/build_ctx_496914074/src/main.c:174:30: error: array type has incomplete element type
 struct mgos_dns_sd_txt_entry hap_service_txt[] = {
                              ^

**Comment by rojer** [comment]
interesting. never happened to me before.
anyway, assuming mgos_homekit.h is from https://github.com/mongoose-os-libs/homekit, i don't recommend using it.
i published it too soon. i found code quality terrible and abandoned it in favor of porting the [official Apple ADK](https://github.com/apple/HomeKitADK).
The port is here: https://github.com/mongoose-os-libs/homekit-adk
it's not finished yet, but will be soon.

**Comment by d4rkmen** [comment]
Yes, it was just a first look in the library
Anyway, dns-sd doesnt seems to work even if i add these lines in example-dns-sd :(
Same error

**Comment by d4rkmen** [comment]
> Anyway, dns-sd doesnt seems to work

Got the point. The example in README.MD uses structur/function not implemented :(

**Comment by d4rkmen** [comment]
git clone and mos clone give different result. mos clone - missing these changes :(

**Comment by d4rkmen** [comment]
Located the source of an issue: the latest commits in **libs** are not used for build. **dns-sd** and also **mongoose**

**Comment by rojer** [comment]
ok, so this is something to do with your setup.
